################
# All the lanes:
################

before_all do
  clear_derived_data
  ENV['DEVELOPER_DIR'] = '/Applications/Xcode.app/Contents/Developer'
end

#################
# iOS only lanes:
#################

platform :ios do
	lane :test do
    scan(
      clean: true,
      scheme: "Ashton",
      device: "iPhone X",
      xcargs: "CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY='' RUN_CLANG_STATIC_ANALYZER=NO IDEBuildOperationMaxNumberOfConcurrentCompileTasks=1"
    )
	end
end


#################
# Mac only lanes:
#################

platform :mac do
	lane :test do
 		scan(
      clean: true,
      scheme: "Ashton",
      destination: "platform=macOS",
			xcargs: "CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY='' RUN_CLANG_STATIC_ANALYZER=NO IDEBuildOperationMaxNumberOfConcurrentCompileTasks=1"
		)
	end
end
